export const MIN_PIE_SLICE_LABEL_ANGLE = 31;

export const MIN_BAR_HEIGHT_FOR_LABEL = 16;

export const MIN_STACKED_BAR_HEIGHT_FOR_LABEL = 14;

export const NEGATIVE_CHART_X_AXIS_OFFSET_MULTIPLIER = 3.5;

export const DEFAULT_HORIZONTAL_BAR_OFFSET = 40;
